# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
hc = HeroClass.create([
  { id: 1, name: "Ant-Man", slug: "ant-man" },
  { id: 2, name: "Black Cat", slug: "" },
  { id: 3, name: "Black Panther", slug: "" },
  { id: 4, name: "Black Widow", slug: "" },
  { id: 5, name: "Blade", slug: "" },
  { id: 6, name: "Cable", slug: "" },
  { id: 7, name: "Captain America", slug: "" },
  { id: 8, name: "Captain Marvel", slug: "" },
  { id: 9, name: "Colossus", slug: "" },
  { id: 10, name: "Cyclops", slug: "" },
  { id: 11, name: "Daredevil", slug: "" },
  { id: 12, name: "Deadpool", slug: "" },
  { id: 13, name: "Doctor Doom", slug: "" },
  { id: 14, name: "Doctor Strange", slug: "" },
  { id: 15, name: "Emma Frost", slug: "" },
  { id: 16, name: "Gambit", slug: "" },
  { id: 17, name: "Ghost Rider", slug: "" },
  { id: 18, name: "Green Goblin", slug: "" },
  { id: 19, name: "Hawkeye", slug: "" },
  { id: 20, name: "Hulk", slug: "" },
  { id: 21, name: "Human Torch", slug: "" },
  { id: 22, name: "Iceman", slug: "" },
  { id: 23, name: "Invisible Woman", slug: "" },
  { id: 24, name: "Iron Fist", slug: "" },
  { id: 25, name: "Iron Man", slug: "" },
  { id: 26, name: "Jean Grey", slug: "" },
  { id: 27, name: "Juggernaut", slug: "" },
  { id: 28, name: "Kitty Pryde", slug: "" },
  { id: 29, name: "Loki", slug: "" },
  { id: 30, name: "Luke Cage", slug: "" },
  { id: 31, name: "Magik", slug: "" },
  { id: 32, name: "Magneto", slug: "" },
  { id: 33, name: "Moon Knight", slug: "" },
  { id: 34, name: "Mr. Fantastic", slug: "" },
  { id: 35, name: "Nightcrawler", slug: "" },
  { id: 36, name: "Nova", slug: "" },
  { id: 37, name: "Psylocke", slug: "" },
  { id: 38, name: "Punisher", slug: "" },
  { id: 39, name: "Rocket Raccoon", slug: "" },
  { id: 40, name: "Rogue", slug: "" },
  { id: 41, name: "Scarlet Witch", slug: "" },
  { id: 42, name: "She-Hulk", slug: "" },
  { id: 43, name: "Silver Surfer", slug: "" },
  { id: 44, name: "Spider-Man", slug: "" },
  { id: 45, name: "Squirrel Girl", slug: "" },
  { id: 46, name: "Star-Lord", slug: "" },
  { id: 47, name: "Storm", slug: "" },
  { id: 48, name: "Taskmaster", slug: "" },
  { id: 49, name: "Thing", slug: "" },
  { id: 50, name: "Thor", slug: "" },
  { id: 51, name: "Venom", slug: "" },
  { id: 52, name: "Vision", slug: "" },
  { id: 53, name: "War Machine", slug: "" },
  { id: 54, name: "Winter Soldier", slug: "" },
  { id: 55, name: "Wolverine", slug: "" },
  { id: 56, name: "X-23", slug: "" },
])
