# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
hc = HeroClass.create([
  { id: 1, name: "Ant-Man", slug: "ant-man" },
  { id: 2, name: "Black Cat", slug: "black-cat" },
  { id: 3, name: "Black Panther", slug: "black-panther" },
  { id: 4, name: "Black Widow", slug: "black-widow" },
  { id: 5, name: "Blade", slug: "blade" },
  { id: 6, name: "Cable", slug: "cable" },
  { id: 7, name: "Captain America", slug: "captain-america" },
  { id: 8, name: "Captain Marvel", slug: "captain-marvel" },
  { id: 9, name: "Colossus", slug: "colossus" },
  { id: 10, name: "Cyclops", slug: "cyclops" },
  { id: 11, name: "Daredevil", slug: "daredevil" },
  { id: 12, name: "Deadpool", slug: "deadpool" },
  { id: 13, name: "Doctor Doom", slug: "doctor-doom" },
  { id: 14, name: "Doctor Strange", slug: "doctor-strange" },
  { id: 15, name: "Emma Frost", slug: "emma-frost" },
  { id: 16, name: "Gambit", slug: "gambit" },
  { id: 17, name: "Ghost Rider", slug: "ghost-rider" },
  { id: 18, name: "Green Goblin", slug: "green-goblin" },
  { id: 19, name: "Hawkeye", slug: "hawkeye" },
  { id: 20, name: "Hulk", slug: "hulk" },
  { id: 21, name: "Human Torch", slug: "human-torch" },
  { id: 22, name: "Iceman", slug: "iceman" },
  { id: 23, name: "Invisible Woman", slug: "invisible-woman" },
  { id: 24, name: "Iron Fist", slug: "iron-fist" },
  { id: 25, name: "Iron Man", slug: "iron-man" },
  { id: 26, name: "Jean Grey", slug: "jean-grey" },
  { id: 27, name: "Juggernaut", slug: "juggernaut" },
  { id: 28, name: "Kitty Pryde", slug: "kitty-pryde" },
  { id: 29, name: "Loki", slug: "loki" },
  { id: 30, name: "Luke Cage", slug: "luke-cage" },
  { id: 31, name: "Magik", slug: "magik" },
  { id: 32, name: "Magneto", slug: "magneto" },
  { id: 33, name: "Moon Knight", slug: "moon-knight" },
  { id: 34, name: "Mr. Fantastic", slug: "mr.-fantastic" },
  { id: 35, name: "Nightcrawler", slug: "nightcrawler" },
  { id: 36, name: "Nova", slug: "nova" },
  { id: 37, name: "Psylocke", slug: "psylocke" },
  { id: 38, name: "Punisher", slug: "punisher" },
  { id: 39, name: "Rocket Raccoon", slug: "rocket-raccoon" },
  { id: 40, name: "Rogue", slug: "rogue" },
  { id: 41, name: "Scarlet Witch", slug: "scarlet-witch" },
  { id: 42, name: "She-Hulk", slug: "she-hulk" },
  { id: 43, name: "Silver Surfer", slug: "silver-surfer" },
  { id: 44, name: "Spider-Man", slug: "spider-man" },
  { id: 45, name: "Squirrel Girl", slug: "squirrel-girl" },
  { id: 46, name: "Star-Lord", slug: "star-lord" },
  { id: 47, name: "Storm", slug: "storm" },
  { id: 48, name: "Taskmaster", slug: "taskmaster" },
  { id: 49, name: "Thing", slug: "thing" },
  { id: 50, name: "Thor", slug: "thor" },
  { id: 51, name: "Venom", slug: "venom" },
  { id: 52, name: "Vision", slug: "vision" },
  { id: 53, name: "War Machine", slug: "war-machine" },
  { id: 54, name: "Winter Soldier", slug: "winter-soldier" },
  { id: 55, name: "Wolverine", slug: "wolverine" },
  { id: 56, name: "X-23", slug: "x-23" },
  { id: 57, name: "Elektra", slug: "elektra" },
])
